# Generated by Django 4.0.6 on 2022-08-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytimesheet',
            name='daily_prod_quant',
            field=models.IntegerField(default=0, verbose_name='Количество выработки за день'),
        ),
        migrations.AddField(
            model_name='dailytimesheet',
            name='rate',
            field=models.IntegerField(default=0, verbose_name='Ставка за работу'),
        ),
        migrations.AddField(
            model_name='dailytimesheet',
            name='stanok',
            field=models.CharField(blank=True, choices=[('ПУ', 'ПУ'), ('ЭВА', 'ЭВА')], max_length=40),
        ),
        migrations.AlterField(
            model_name='dailyproduction',
            name='package',
            field=models.IntegerField(blank=True, verbose_name='Упаковка'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacture.catalogue', verbose_name='Mодель'),
        ),
    ]
