# Generated by Django 4.0.6 on 2022-08-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0002_dailytimesheet_daily_prod_quant_dailytimesheet_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytimesheet',
            name='rate_day',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
