# Generated by Django 4.0.6 on 2022-08-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacture', '0003_dailytimesheet_rate_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterField(
            model_name='dailytimesheet',
            name='rate_day',
            field=models.PositiveIntegerField(blank=True, verbose_name='Модель'),
        ),
    ]
